Домашка по 4-му уроку
eugene-okulik/Alex57 pull request #4
Opened 2024-12-21 13:25 UTC by donic57

@eugene-okulik Привет! Скинул домашнюю работу по 4-му уроку, проверь пожалуйста.

2024-12-22 10:04 UTC, eugene-okulik requested changes
Всё отлично, но проверку на внимательность не прошел ))

2024-12-22 10:04 UTC, eugene-okulik commented on homework/aleksey_lyadov/Homework_4/Homework_4.py
> +my_dict['dict']['i am a tuple'] = 'gdgdfgergddh'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-12-22 15:14 UTC, donic57 commented
@eugene-okulik Ага, спасибо за поправку, исправил!

2024-12-23 06:34 UTC, eugene-okulik approved these changes

2024-12-23 06:34 UTC, merged